// Generated by CoffeeScript 1.4.0

/*
This is argument parser helper mixin
*/


(function() {
  var getItType, instanceProperties;

  getItType = require("../lib/type_detector").getItType;

  module.exports = instanceProperties = {
    /*
      This method parse arg and may ensure its type
    */

    _argParser: function(arg, arg_name, strict_type) {
      var arg_type, err_formatter, parsed_arg;
      err_formatter = function(err_string, arg_type) {
        return "" + err_string + "\n|arg_name| = |" + arg_name + "|\n|type| = |" + arg_type + "|\n|arg|   = |" + arg + "|";
      };
      parsed_arg = (function() {
        switch (arg_type = getItType(arg)) {
          case 'STRING':
            try {
              return ['REGEXP', RegExp(arg)];
            } catch (error) {
              throw SyntaxError(err_formatter("cant compile this String to RegExp", arg_type));
            }
            break;
          case 'REGEXP':
            return ['REGEXP', arg];
          case 'FUNCTION':
            return ['FUNCTION', arg];
          default:
            throw TypeError(err_formatter("argument must be String, RegExp or Function, but got", arg_type));
        }
      })();
      if ((strict_type != null) && parsed_arg[0] !== strict_type.toUpperCase()) {
        throw TypeError(err_formatter("argument must be " + strict_type + ", but got", arg_type));
      }
      return parsed_arg;
    }
  };

}).call(this);
